/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.28.                           *
*        Compiled Jan 30 2015, 16:40:04                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: volume_medium                                         *
* Dimensions:  20 * 15                                               *
* NumColors:   16                                                    *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmvolume_medium;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsvolume_medium[] = {
  0x000000, 0x111111, 0x222222, 0x333333,
  0x444444, 0x555555, 0x666666, 0x777777,
  0x888888, 0x999999, 0xAAAAAA, 0xBBBBBB,
  0xCCCCCC, 0xDDDDDD, 0xEEEEEE, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palvolume_medium = {
  16,  // Number of entries
  0,   // No transparency
  &_Colorsvolume_medium[0]
};

static GUI_CONST_STORAGE unsigned char _acvolume_medium[] = {
  /* RLE: 008 Pixels @ 000,000 */ 8, 0x0F, 
  /* ABS: 003 Pixels @ 008,000 */ 0, 3, 0x80, 0xC0, 
  /* RLE: 015 Pixels @ 011,000 */ 15, 0x0F, 
  /* ABS: 005 Pixels @ 006,001 */ 0, 5, 0xE4, 0x00, 0xC0, 
  /* RLE: 014 Pixels @ 011,001 */ 14, 0x0F, 
  /* ABS: 006 Pixels @ 005,002 */ 0, 6, 0xB1, 0x00, 0x0C, 
  /* RLE: 004 Pixels @ 011,002 */ 4, 0x0F, 
  /* ABS: 003 Pixels @ 015,002 */ 0, 3, 0x52, 0x90, 
  /* RLE: 006 Pixels @ 018,002 */ 6, 0x0F, 
  /* RLE: 001 Pixels @ 004,003 */ 1, 0x07, 
  /* RLE: 005 Pixels @ 005,003 */ 5, 0x00, 
  /* ABS: 014 Pixels @ 010,003 */ 0, 14, 0xCD, 0x9E, 0xF5, 0x00, 0x8F, 0x22, 0x21, 
  /* RLE: 006 Pixels @ 004,004 */ 6, 0x00, 
  /* ABS: 010 Pixels @ 010,004 */ 0, 10, 0xC4, 0x01, 0xDF, 0x60, 0x0C, 
  /* RLE: 010 Pixels @ 000,005 */ 10, 0x00, 
  /* ABS: 010 Pixels @ 010,005 */ 0, 10, 0xCD, 0x10, 0x2F, 0xF1, 0x04, 
  /* RLE: 010 Pixels @ 000,006 */ 10, 0x00, 
  /* ABS: 008 Pixels @ 010,006 */ 0, 8, 0xCF, 0xB0, 0x0B, 0xF8, 
  /* RLE: 012 Pixels @ 018,006 */ 12, 0x00, 
  /* ABS: 008 Pixels @ 010,007 */ 0, 8, 0xCF, 0xE0, 0x0A, 0xF9, 
  /* RLE: 012 Pixels @ 018,007 */ 12, 0x00, 
  /* ABS: 008 Pixels @ 010,008 */ 0, 8, 0xCF, 0xB0, 0x0B, 0xF8, 
  /* RLE: 012 Pixels @ 018,008 */ 12, 0x00, 
  /* ABS: 014 Pixels @ 010,009 */ 0, 14, 0xCD, 0x10, 0x2F, 0xF2, 0x04, 0x22, 0x21, 
  /* RLE: 006 Pixels @ 004,010 */ 6, 0x00, 
  /* ABS: 010 Pixels @ 010,010 */ 0, 10, 0xC4, 0x01, 0xDF, 0x60, 0x0C, 
  /* RLE: 004 Pixels @ 000,011 */ 4, 0x0F, 
  /* RLE: 001 Pixels @ 004,011 */ 1, 0x07, 
  /* RLE: 005 Pixels @ 005,011 */ 5, 0x00, 
  /* ABS: 009 Pixels @ 010,011 */ 0, 9, 0xCD, 0x9E, 0xF5, 0x00, 0x80, 
  /* RLE: 006 Pixels @ 019,011 */ 6, 0x0F, 
  /* ABS: 006 Pixels @ 005,012 */ 0, 6, 0xB1, 0x00, 0x0C, 
  /* RLE: 004 Pixels @ 011,012 */ 4, 0x0F, 
  /* ABS: 003 Pixels @ 015,012 */ 0, 3, 0x52, 0x90, 
  /* RLE: 008 Pixels @ 018,012 */ 8, 0x0F, 
  /* ABS: 005 Pixels @ 006,013 */ 0, 5, 0xE4, 0x00, 0xC0, 
  /* RLE: 017 Pixels @ 011,013 */ 17, 0x0F, 
  /* ABS: 003 Pixels @ 008,014 */ 0, 3, 0x80, 0xC0, 
  /* RLE: 009 Pixels @ 011,014 */ 9, 0x0F, 
  0
};  // 144 bytes for 300 pixels

GUI_CONST_STORAGE GUI_BITMAP bmvolume_medium = {
  20, // xSize
  15, // ySize
  10, // BytesPerLine
  GUI_COMPRESS_RLE4, // BitsPerPixel
  _acvolume_medium,  // Pointer to picture data (indices)
  &_Palvolume_medium,  // Pointer to palette
  GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
