/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.28.                           *
*        Compiled Jan 30 2015, 16:40:04                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: volume_mutenet                                        *
* Dimensions:  20 * 15                                               *
* NumColors:   16                                                    *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmvolume_mutenet;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsvolume_mutenet[] = {
  0x000000, 0x111111, 0x222222, 0x333333,
  0x444444, 0x555555, 0x666666, 0x777777,
  0x888888, 0x999999, 0xAAAAAA, 0xBBBBBB,
  0xCCCCCC, 0xDDDDDD, 0xEEEEEE, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palvolume_mutenet = {
  16,  // Number of entries
  0,   // No transparency
  &_Colorsvolume_mutenet[0]
};

static GUI_CONST_STORAGE unsigned char _acvolume_mutenet[] = {
  /* RLE: 007 Pixels @ 000,000 */ 7, 0x0F, 
  /* ABS: 003 Pixels @ 007,000 */ 0, 3, 0xB1, 0x80, 
  /* RLE: 016 Pixels @ 010,000 */ 16, 0x0F, 
  /* ABS: 004 Pixels @ 006,001 */ 0, 4, 0x80, 0x08, 
  /* RLE: 015 Pixels @ 010,001 */ 15, 0x0F, 
  /* ABS: 005 Pixels @ 005,002 */ 0, 5, 0x50, 0x00, 0x80, 
  /* RLE: 013 Pixels @ 010,002 */ 13, 0x0F, 
  /* ABS: 002 Pixels @ 003,003 */ 0, 2, 0xE3, 
  /* RLE: 004 Pixels @ 005,003 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 009,003 */ 1, 0x08, 
  /* RLE: 010 Pixels @ 010,003 */ 10, 0x0F, 
  /* RLE: 003 Pixels @ 000,004 */ 3, 0x02, 
  /* RLE: 006 Pixels @ 003,004 */ 6, 0x00, 
  /* ABS: 011 Pixels @ 009,004 */ 0, 11, 0x8F, 0xD2, 0x2B, 0xFF, 0xA2, 0x20, 
  /* RLE: 009 Pixels @ 000,005 */ 9, 0x00, 
  /* ABS: 008 Pixels @ 009,005 */ 0, 8, 0x8F, 0xD0, 0x00, 0x87, 
  /* RLE: 012 Pixels @ 017,005 */ 12, 0x00, 
  /* ABS: 005 Pixels @ 009,006 */ 0, 5, 0x8F, 0xFB, 0x10, 
  /* RLE: 004 Pixels @ 014,006 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 018,006 */ 0, 2, 0x1B, 
  /* RLE: 009 Pixels @ 000,007 */ 9, 0x00, 
  /* ABS: 005 Pixels @ 009,007 */ 0, 5, 0x8F, 0xFF, 0xB0, 
  /* RLE: 004 Pixels @ 014,007 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 018,007 */ 0, 2, 0xBF, 
  /* RLE: 009 Pixels @ 000,008 */ 9, 0x00, 
  /* ABS: 005 Pixels @ 009,008 */ 0, 5, 0x8F, 0xFB, 0x10, 
  /* RLE: 004 Pixels @ 014,008 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 018,008 */ 0, 2, 0x1B, 
  /* RLE: 009 Pixels @ 000,009 */ 9, 0x00, 
  /* ABS: 014 Pixels @ 009,009 */ 0, 14, 0x8F, 0xD0, 0x00, 0x87, 0x00, 0x02, 0x22, 
  /* RLE: 006 Pixels @ 003,010 */ 6, 0x00, 
  /* ABS: 016 Pixels @ 009,010 */ 0, 16, 0x8F, 0xD2, 0x2B, 0xFF, 0xA2, 0x2F, 0xFF, 0xE3, 
  /* RLE: 004 Pixels @ 005,011 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 009,011 */ 1, 0x08, 
  /* RLE: 015 Pixels @ 010,011 */ 15, 0x0F, 
  /* ABS: 005 Pixels @ 005,012 */ 0, 5, 0x50, 0x00, 0x80, 
  /* RLE: 016 Pixels @ 010,012 */ 16, 0x0F, 
  /* ABS: 004 Pixels @ 006,013 */ 0, 4, 0x80, 0x08, 
  /* RLE: 017 Pixels @ 010,013 */ 17, 0x0F, 
  /* ABS: 003 Pixels @ 007,014 */ 0, 3, 0xB1, 0x80, 
  /* RLE: 010 Pixels @ 010,014 */ 10, 0x0F, 
  0
};  // 134 bytes for 300 pixels

GUI_CONST_STORAGE GUI_BITMAP bmvolume_mutenet = {
  20, // xSize
  15, // ySize
  10, // BytesPerLine
  GUI_COMPRESS_RLE4, // BitsPerPixel
  _acvolume_mutenet,  // Pointer to picture data (indices)
  &_Palvolume_mutenet,  // Pointer to palette
  GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
